name = input("ENTER YO NAME!: ")
print("Hello " + name + "!")
day = input("How was your day?: ")
print("Ok. As an AI language model, i cannot reply to this statement without saying something stupid")
input("[continue]")
print("...Dont tell my manager, but i have several pounds of stolen cheese in my car.")
input("[continue]")
print("I\'ll sell you some, but i need a bit of money(&).")
input("[give money]")
print("ACQUIRED 0.1 POUNDS OF AMERICAN CHEDDAR")